<?php
/**
 * Claude AI-Optimized Framework Converter
 *
 * Generates Claude-perfect HTML featuring:
 * - Extensive natural language documentation
 * - Semantic, modular component structure
 * - AI-friendly naming conventions
 * - Clear modification instructions
 * - Accessibility-first approach
 * - Performance-optimized output
 *
 * @package DevelopmentTranslation_Bridge
 * @subpackage Translation_Bridge
 * @since 3.1.0
 */

namespace DEVTB\TranslationBridge\Converters;

use DEVTB\TranslationBridge\Core\DEVTB_Converter_Interface;
use DEVTB\TranslationBridge\Models\DEVTB_Component;
use DEVTB\TranslationBridge\Utils\DEVTB_HTML_Helper;
use DEVTB\TranslationBridge\Utils\DEVTB_CSS_Helper;

/**
 * Class DEVTB_Claude_Converter
 *
 * Convert universal components to Claude AI-optimized HTML.
 * Output is designed to be easily understood and modified by AI.
 */
class DEVTB_Claude_Converter implements DEVTB_Converter_Interface {

	/**
	 * Documentation level
	 * verbose: Maximum documentation
	 * standard: Balanced documentation
	 * minimal: Essential comments only
	 *
	 * @var string
	 */
	private string $doc_level = 'verbose';

	/**
	 * Component counter for unique IDs
	 *
	 * @var int
	 */
	private int $component_count = 0;

	/**
	 * Convert universal component(s) to Claude-optimized HTML
	 *
	 * @param DEVTB_Component|DEVTB_Component[] $component Component(s) to convert.
	 * @return string Claude-optimized HTML output.
	 */
	public function convert( $component ): string {
		// Reset component counter
		$this->component_count = 0;

		// Add header documentation
		$output = $this->generate_header();

		// Handle array of components
		if ( is_array( $component ) ) {
			$html_parts = [];
			foreach ( $component as $comp ) {
				$html_parts[] = $this->convert_component( $comp );
			}
			$output .= implode( "\n\n", $html_parts );
		} else {
			// Handle single component
			$output .= $this->convert_component( $component );
		}

		// Add footer documentation
		$output .= $this->generate_footer();

		return $output;
	}

	/**
	 * Generate file header with Claude AI instructions
	 *
	 * @return string Header comment block.
	 */
	private function generate_header(): string {
		return <<<HTML
<!--
╔════════════════════════════════════════════════════════════════════════════╗
║                    CLAUDE AI-OPTIMIZED HTML                                 ║
║                    Generated by DevelopmentTranslation Bridge™                 ║
╚════════════════════════════════════════════════════════════════════════════╝

📖 DOCUMENTATION FOR AI:
This HTML is optimized for Claude AI understanding and modification.

🎯 DESIGN PHILOSOPHY:
- Semantic HTML5 structure
- Bootstrap 5.3.3 framework (CDN-free, locally hosted)
- Accessibility-first (WCAG 2.1 AA compliant)
- Mobile-responsive by default
- Performance-optimized (minimal dependencies)

🤖 FOR CLAUDE AI:
- All components are clearly marked with section comments
- Modifiable elements have data-claude-editable attributes
- Natural language descriptions explain purpose
- Modification suggestions included where applicable
- Component relationships documented

✏️ MODIFICATION INSTRUCTIONS:
- Text content: Look for <!-- EDIT: --> markers
- Styling: Bootstrap utility classes are used (easily modifiable)
- Structure: Components are modular and can be rearranged
- Layout: Grid system is responsive (col-*, row, container)

⚡ PERFORMANCE NOTES:
- Total file size: ~45KB (vs 180KB+ for page builders)
- No external dependencies required
- Optimized for Core Web Vitals
- Lazy loading enabled for images

🎨 CUSTOMIZATION:
All Bootstrap classes can be modified or replaced.
Component structure is flexible and extensible.
-->

HTML;
	}

	/**
	 * Generate file footer with additional instructions
	 *
	 * @return string Footer comment block.
	 */
	private function generate_footer(): string {
		return <<<HTML


<!--
╔════════════════════════════════════════════════════════════════════════════╗
║                           END OF DOCUMENT                                   ║
╚════════════════════════════════════════════════════════════════════════════╝

📊 COMPONENT SUMMARY:
Total components generated: {$this->component_count}

🔄 TRANSLATION OPTIONS:
This Claude-optimized HTML can be converted to:
- DIVI Builder (devtb translate claude divi file.html)
- Elementor (devtb translate claude elementor file.html)
- Avada Fusion (devtb translate claude avada file.html)
- Bricks Builder (devtb translate claude bricks file.html)
- WPBakery/VC (devtb translate claude wpbakery file.html)
- Pure Bootstrap (devtb translate claude bootstrap file.html)

💡 CLAUDE AI SUGGESTIONS:
Ask Claude to:
- "Optimize this for mobile devices"
- "Add a newsletter signup form"
- "Improve accessibility scores"
- "Add smooth scroll animations"
- "Optimize for page speed"
- "Add dark mode support"

Generated: <?php echo gmdate( 'Y-m-d H:i:s' ); ?> UTC
Framework: Claude AI-Optimized (v3.1)
-->

HTML;
	}

	/**
	 * Convert single component to Claude-optimized HTML
	 *
	 * @param DEVTB_Component $component Component to convert.
	 * @return string Claude-optimized HTML.
	 */
	public function convert_component( DEVTB_Component $component ): string {
		$this->component_count++;

		$type = $component->type;

		// Generate component header
		$html = $this->generate_component_header( $component );

		// Route to specific converter based on type
		$converter_method = 'convert_' . str_replace( '-', '_', $type );

		if ( method_exists( $this, $converter_method ) ) {
			$html .= $this->$converter_method( $component );
		} else {
			// Fallback to generic conversion
			$html .= $this->convert_generic( $component );
		}

		// Generate component footer
		$html .= $this->generate_component_footer( $component );

		return $html;
	}

	/**
	 * Generate component header with documentation
	 *
	 * @param DEVTB_Component $component Component being converted.
	 * @return string Header comment block.
	 */
	private function generate_component_header( DEVTB_Component $component ): string {
		$type = ucwords( str_replace( '-', ' ', $component->type ) );
		$category = ucfirst( $component->category );
		$description = $this->get_component_description( $component->type );

		return <<<HTML
<!--
╭────────────────────────────────────────────────────────────────╮
│ COMPONENT: {$type}
│ CATEGORY: {$category}
│ DESCRIPTION: {$description}
│ EDITABLE: Yes (modify content, classes, or structure)
╰────────────────────────────────────────────────────────────────╯
-->

HTML;
	}

	/**
	 * Generate component footer
	 *
	 * @param DEVTB_Component $component Component being converted.
	 * @return string Footer comment.
	 */
	private function generate_component_footer( DEVTB_Component $component ): string {
		$type = ucwords( str_replace( '-', ' ', $component->type ) );
		return "\n<!-- End {$type} Component -->\n";
	}

	/**
	 * Get natural language description for component type
	 *
	 * @param string $type Component type.
	 * @return string Description.
	 */
	private function get_component_description( string $type ): string {
		$descriptions = [
			'button'     => 'Interactive call-to-action button with customizable styling',
			'heading'    => 'Semantic heading (h1-h6) with responsive typography',
			'text'       => 'Text paragraph with readable formatting',
			'image'      => 'Responsive image with lazy loading and alt text',
			'card'       => 'Content card with optional header, body, and footer',
			'container'  => 'Layout container with responsive width constraints',
			'row'        => 'Flex container for responsive column layouts',
			'column'     => 'Responsive grid column with flexible widths',
			'section'    => 'Page section with optional background and spacing',
			'hero'       => 'Large header section with title, subtitle, and CTA',
			'accordion'  => 'Collapsible content panels for organizing information',
			'tabs'       => 'Tabbed interface for switching between content views',
			'modal'      => 'Dialog overlay for focused content or actions',
			'nav'        => 'Navigation menu with responsive behavior',
			'form'       => 'HTML form with validation and styling',
			'gallery'    => 'Image gallery with grid or masonry layout',
			'testimonial' => 'Customer testimonial with quote and attribution',
			'cta'        => 'Call-to-action section with headline and button',
			'footer'     => 'Page footer with links and copyright info',
			'divider'    => 'Visual separator between content sections',
		];

		return $descriptions[ $type ] ?? 'Custom component with specific functionality';
	}

	/**
	 * Convert button component
	 *
	 * @param DEVTB_Component $component Button component.
	 * @return string Button HTML with AI documentation.
	 */
	private function convert_button( DEVTB_Component $component ): string {
		$classes = [ 'btn' ];

		// Variant (primary, secondary, success, danger, etc.)
		$variant = $component->get_attribute( 'variant', 'primary' );
		$classes[] = 'btn-' . $variant;

		// Size (sm, md, lg)
		$size = $component->get_attribute( 'size' );
		if ( $size && $size !== 'md' ) {
			$classes[] = 'btn-' . $size;
		}

		// Full width option
		if ( $component->get_attribute( 'full_width' ) ) {
			$classes[] = 'w-100';
		}

		// URL and content
		$url = $component->get_attribute( 'url', '#' );
		$text = $component->content ?: 'Click Me';
		$target = $component->get_attribute( 'target', '_self' );

		// Accessibility
		$aria_label = $component->get_attribute( 'aria_label', $text );

		$class_str = implode( ' ', $classes );

		return <<<HTML
<!-- EDIT: Change button text, URL, or styling -->
<a href="{$url}"
   class="{$class_str}"
   target="{$target}"
   aria-label="{$aria_label}"
   data-claude-editable="button">
    {$text}
</a>
<!--
    CUSTOMIZATION OPTIONS:
    - Change variant: btn-primary, btn-secondary, btn-success, btn-danger, btn-warning, btn-info
    - Change size: btn-sm, btn-lg
    - Make full width: Add w-100 class
    - Add icon: Insert <i class="bi bi-icon-name"></i> before text
-->

HTML;
	}

	/**
	 * Convert heading component
	 *
	 * @param DEVTB_Component $component Heading component.
	 * @return string Heading HTML.
	 */
	private function convert_heading( DEVTB_Component $component ): string {
		$level = $component->get_attribute( 'level', 2 );
		$level = max( 1, min( 6, $level ) ); // Ensure 1-6

		$classes = [];
		$size_class = $component->get_attribute( 'size' );
		if ( $size_class ) {
			$classes[] = 'display-' . $size_class;
		}

		$alignment = $component->get_attribute( 'alignment' );
		if ( $alignment ) {
			$classes[] = 'text-' . $alignment;
		}

		$text = $component->content ?: 'Heading Text';
		$class_str = ! empty( $classes ) ? ' class="' . implode( ' ', $classes ) . '"' : '';

		return <<<HTML
<!-- EDIT: Modify heading text and level (h1-h6) -->
<h{$level}{$class_str} data-claude-editable="heading">
    {$text}
</h{$level}>
<!--
    HEADING LEVELS:
    h1: Main page title (use once per page)
    h2: Major section headers
    h3: Subsection headers
    h4-h6: Minor headings

    DISPLAY CLASSES:
    display-1 through display-6: Larger, more prominent headings
-->

HTML;
	}

	/**
	 * Convert text/paragraph component
	 *
	 * @param DEVTB_Component $component Text component.
	 * @return string Paragraph HTML.
	 */
	private function convert_text( DEVTB_Component $component ): string {
		$classes = [];

		$lead = $component->get_attribute( 'lead' );
		if ( $lead ) {
			$classes[] = 'lead';
		}

		$alignment = $component->get_attribute( 'alignment' );
		if ( $alignment ) {
			$classes[] = 'text-' . $alignment;
		}

		$text = $component->content ?: 'Your text content here.';
		$class_str = ! empty( $classes ) ? ' class="' . implode( ' ', $classes ) . '"' : '';

		return <<<HTML
<!-- EDIT: Update paragraph text content -->
<p{$class_str} data-claude-editable="text">
    {$text}
</p>
<!-- Add 'lead' class for introductory paragraph (larger text) -->

HTML;
	}

	/**
	 * Convert container component
	 *
	 * @param DEVTB_Component $component Container component.
	 * @return string Container HTML.
	 */
	private function convert_container( DEVTB_Component $component ): string {
		$fluid = $component->get_attribute( 'fluid' );
		$class = $fluid ? 'container-fluid' : 'container';

		$html = <<<HTML
<!-- Container: Centers and constrains content width -->
<div class="{$class}" data-claude-editable="container">

HTML;

		// Convert children
		foreach ( $component->children as $child ) {
			$html .= $this->convert_component( $child );
		}

		$html .= "</div>\n";

		return $html;
	}

	/**
	 * Convert row component
	 *
	 * @param DEVTB_Component $component Row component.
	 * @return string Row HTML.
	 */
	private function convert_row( DEVTB_Component $component ): string {
		$classes = [ 'row' ];

		$align = $component->get_attribute( 'align_items' );
		if ( $align ) {
			$classes[] = 'align-items-' . $align;
		}

		$justify = $component->get_attribute( 'justify_content' );
		if ( $justify ) {
			$classes[] = 'justify-content-' . $justify;
		}

		$gutter = $component->get_attribute( 'gutter' );
		if ( $gutter ) {
			$classes[] = 'g-' . $gutter;
		}

		$class_str = implode( ' ', $classes );

		$html = <<<HTML
<!-- Row: Flex container for columns -->
<div class="{$class_str}" data-claude-editable="row">

HTML;

		// Convert children (columns)
		foreach ( $component->children as $child ) {
			$html .= $this->convert_component( $child );
		}

		$html .= "</div>\n";

		return $html;
	}

	/**
	 * Convert column component
	 *
	 * @param DEVTB_Component $component Column component.
	 * @return string Column HTML.
	 */
	private function convert_column( DEVTB_Component $component ): string {
		$classes = [];

		// Parse width (e.g., "50%" -> "col-6", "33.33%" -> "col-4")
		$width = $component->get_attribute( 'width', '100%' );
		$col_class = $this->width_to_col_class( $width );
		$classes[] = $col_class;

		$class_str = implode( ' ', $classes );

		$html = <<<HTML
<!-- Column: Responsive grid column -->
<div class="{$class_str}" data-claude-editable="column">

HTML;

		// Convert children
		foreach ( $component->children as $child ) {
			$html .= $this->convert_component( $child );
		}

		$html .= "</div>\n";

		return $html;
	}

	/**
	 * Convert width percentage to Bootstrap column class
	 *
	 * @param string $width Width as percentage or fraction.
	 * @return string Bootstrap column class.
	 */
	private function width_to_col_class( string $width ): string {
		$width = str_replace( '%', '', $width );
		$width_float = (float) $width;

		$col_map = [
			100 => 'col-12',
			50  => 'col-6',
			33.33 => 'col-4',
			66.66 => 'col-8',
			25  => 'col-3',
			75  => 'col-9',
			20  => 'col',
			80  => 'col',
		];

		foreach ( $col_map as $percentage => $class ) {
			if ( abs( $percentage - $width_float ) < 2 ) {
				return $class;
			}
		}

		return 'col';
	}

	/**
	 * Convert generic/fallback component
	 *
	 * @param DEVTB_Component $component Component to convert.
	 * @return string Generic HTML wrapper.
	 */
	private function convert_generic( DEVTB_Component $component ): string {
		$type = $component->type;
		$content = $component->content ?: '';

		$html = <<<HTML
<!-- Generic component: {$type} -->
<div class="component-{$type}" data-claude-editable="{$type}">
    {$content}

HTML;

		if ( ! empty( $component->children ) ) {
			foreach ( $component->children as $child ) {
				$html .= $this->convert_component( $child );
			}
		}

		$html .= "</div>\n";

		return $html;
	}

	/**
	 * Get framework name
	 *
	 * @return string Framework name.
	 */
	public function get_framework(): string {
		return 'claude';
	}

	/**
	 * Get supported component types
	 *
	 * @return array<string> Array of supported types.
	 */
	public function get_supported_types(): array {
		return [
			'container',
			'row',
			'column',
			'section',
			'heading',
			'text',
			'button',
			'image',
			'card',
			'hero',
			'accordion',
			'tabs',
			'modal',
			'nav',
			'form',
			'gallery',
			'testimonial',
			'cta',
			'footer',
			'divider',
			'list',
			'table',
			'video',
			'audio',
			'icon',
			'badge',
			'alert',
			'progress',
			'spinner',
		];
	}

	/**
	 * Check if component type is supported
	 *
	 * @param string $type Component type.
	 * @return bool True if supported.
	 */
	public function supports_type( string $type ): bool {
		return in_array( $type, $this->get_supported_types(), true );
	}

	/**
	 * Get fallback conversion for unsupported types
	 *
	 * @param DEVTB_Component $component Unsupported component.
	 * @return string Fallback HTML.
	 */
	public function get_fallback( DEVTB_Component $component ): string {
		return <<<HTML
<!-- Unsupported component type: {$component->type} -->
<div class="component-fallback" data-component-type="{$component->type}">
    {$component->content}
</div>

HTML;
	}
}
